typo

diff --git a/bin/chkSysPython b/bin/chkSysPython
--- a/bin/chkSysPython
+++ b/bin/chkSysPython
@@ -6,15 +6,15 @@ die(){
 }
 
 if [ "_${1}" != "_" ]; then
-    test -x $1 && PYTHON=$1
+    test -e $1 && PYTHON=$1 || die "ERROR: $1 missing"
 else
     PYTHON=/usr/bin/python
 fi
 
-test -f ${PYTHON} || die "ERROR: system python missing"
-$(${PYTHON} -V 2>&1 | awk '{print $2}' | awk -F \. '{
-if ((10*$1+$2)<27) print "ERROR: system python is too old";
-}')
-$(${PYTHON} -V 2>&1 | awk '{print $2}' | awk -F \. '{
-if ((10*$1+$2)>29) print "ERROR: system python3 is not supported";
-}')
+test -e ${PYTHON} || die "ERROR: system python missing"
+`${PYTHON} -V 2>&1 | awk '{print $2}' | awk -F \. '{
+if ((10*$1+$2)<27) print "die ERROR: system python is too old";
+}'`
+`${PYTHON} -V 2>&1 | awk '{print $2}' | awk -F \. '{
+if ((10*$1+$2)>29) print "die ERROR: system python3 is not supported";
+}'`
