easteregg

diff --git a/bin/chkSysPython b/bin/chkSysPython
--- a/bin/chkSysPython
+++ b/bin/chkSysPython
@@ -5,10 +5,16 @@ die(){
     exit 1
 }
 
-test -f /usr/bin/python || die "ERROR: system python missing"
-$(/usr/bin/python -V 2>&1 | awk '{print $2}' | awk -F \. '{
+if [ "_${1}" != "_" ]; then
+    test -x $1 && PYTHON=$1
+else
+    PYTHON=/usr/bin/python
+fi
+
+test -f ${PYTHON} || die "ERROR: system python missing"
+$(${PYTHON} -V 2>&1 | awk '{print $2}' | awk -F \. '{
 if ((10*$1+$2)<27) print "ERROR: system python is too old";
 }')
-$(/usr/bin/python -V 2>&1 | awk '{print $2}' | awk -F \. '{
+$(${PYTHON} -V 2>&1 | awk '{print $2}' | awk -F \. '{
 if ((10*$1+$2)>29) print "ERROR: system python3 is not supported";
 }')
