refactoring

diff --git a/bin/uninstall b/bin/uninstall
--- a/bin/uninstall
+++ b/bin/uninstall
@@ -6,7 +6,7 @@
 #              2. package file itself gets removed
 
 # utility for log
-die{}{
+die(){
     test "$*" && echo "$*" || true
     exit 1
 }
@@ -17,7 +17,7 @@ if [ "$#" -ne 1 ]; then
 fi
 
 # 1. check PREFIX
-test "${PREFIX}" || die "[ERROR] PREFIX is not set, try PREFIX=foo bin/uninstall"
+test "${PREFIX}" || die "[ERROR] PREFIX is not set or empty, try PREFIX=foo bin/uninstall"
 test -d "${PREFIX}/var/pkg" || die "[ERROR] package database not found"
 
 # 2. check pkg
@@ -26,7 +26,7 @@ test -f "${PREFIX}/var/pkg/$1" || die "[ERROR] package not found"
 # 3. remove files
 cd ${PREFIX} || die "[ERROR] Sum Ting Wong, Wi Tu Lo."
 # beware of the space in the path list in the package file
-IFS=${echo -en "\n\b"}
+IFS=$(echo -en "\n\b")
 for thisFile in `cat var/pkg/${1}`; do
     test -d $thisFile && find $thidFile -empty -delete || true
     test -f $thisFile && rm -f $thisFile || true
